### ISSUE TITLE
Remove defaults

### ISSUE THREAD

**Issue by vuxor** [tatjama/uteam-api#3]
https://github.com/tatjama/uteam-api/blob/5c61d452f597e61fbe65af0252d37db738c02398/src/instances/sequalize.ts#L8

Let's just remove default values for DB name, username and password.
You can leave port.

**Comment by tatjama** [comment]
@vuxor  I removed default values for DB name, username and password
https://github.com/tatjama/uteam-api/blob/b530df5a76a6c0823ddc38def712e9499ffc9de0/src/instances/sequalize.ts#L4
and also removed default value for jwtSecret
https://github.com/tatjama/uteam-api/blob/b530df5a76a6c0823ddc38def712e9499ffc9de0/src/auth/auth.jwt.ts#L5
I hope it is O.K. now.

**Comment by vuxor** [comment]
LGTM
