### ISSUE TITLE
Sanitise

### ISSUE THREAD

**Issue by vuxor** [tatjama/uteam-api#4]
https://github.com/tatjama/uteam-api/blob/5c61d452f597e61fbe65af0252d37db738c02398/src/controllers/users.controller.ts#L21

We should always sanitise user input. Please check for valid email address and also check for non valid chars in username.

**Comment by tatjama** [comment]
@vuxor 
I hope it's okay to use the validator-express library with constraints that the username starts with a letter and contains only letters, numbers or #% -_ * characters.
If this is not the case and I need to do a custom validation, please let me know.

https://github.com/tatjama/uteam-api/blob/b530df5a76a6c0823ddc38def712e9499ffc9de0/src/routes/users.routes.ts#L21
https://github.com/tatjama/uteam-api/blob/b530df5a76a6c0823ddc38def712e9499ffc9de0/src/middleware/users.middleware.ts#L8

![errors-register](https://user-images.githubusercontent.com/43373641/148755279-09bbaafb-0f3c-47c9-bab4-cd7feebd9b91.png)
![errors-login](https://user-images.githubusercontent.com/43373641/148755664-654f0855-65c8-4632-9088-9b3ca8d778f2.png)

**Comment by vuxor** [comment]
You can use validator lib

**Comment by tatjama** [comment]
@vuxor 
I used validator library for user input validation.

https://github.com/tatjama/uteam-api/blob/13a684157ae0e0466b48467f923ee52986cef75a/src/middleware/users.middleware.ts#L25

https://github.com/tatjama/uteam-api/blob/13a684157ae0e0466b48467f923ee52986cef75a/src/routes/users.routes.ts#L15

Example Error user register

![errors-register](https://user-images.githubusercontent.com/43373641/149101508-6a25af26-cbb6-4b82-b461-8c66d4fec6ab.png)

Example Error user login

![errors-login](https://user-images.githubusercontent.com/43373641/149098592-a397caf0-f152-4831-8f16-e65a6b2ab32c.png)

If I need to change anything, please let me know.
